# name: Cargo tests

# on: [ push, pull_request ]

# jobs:
#   cargo_build_wasm:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#     steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          target: wasm32-unknown-unknown
#      - run: cargo build --release --target wasm32-unknown-unknown
#   cargo_test:
#     runs-on: ubuntu-latest

#     steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#      - run: ./run-test.sh
